import Foundation

// MARK: - MockData
enum MockData {

    // MARK: Categories
    static let categories: [RestaurantCategory] = [
        RestaurantCategory(id: "all",      label: "All",      icon: "square.grid.2x2"),
        RestaurantCategory(id: "burgers",  label: "Burgers",  icon: "fork.knife"),
        RestaurantCategory(id: "pizza",    label: "Pizza",    icon: "flame"),
        RestaurantCategory(id: "grills",   label: "Grills",   icon: "flame.fill"),
        RestaurantCategory(id: "sushi",    label: "Sushi",    icon: "fish"),
        RestaurantCategory(id: "tacos",    label: "Tacos",    icon: "leaf"),
        RestaurantCategory(id: "salads",   label: "Salads",   icon: "leaf.fill"),
        RestaurantCategory(id: "desserts", label: "Desserts", icon: "birthday.cake"),
        RestaurantCategory(id: "drinks",   label: "Drinks",   icon: "cup.and.saucer"),
    ]

    // MARK: Al Taib Menu
    static let alTaibMenu: [MenuItem] = [

        // ── Create Your Bowl ────────────────────────────────────────────
        MenuItem(id: "altaib-bowl-500",  name: "Create Your Bowl (500 G)",
                 description: "Pick up to 5 items of approximately 100 grams each.",
                 price: 12.50,
                 image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
                 popular: true, section: "Create Your Bowl"),
        MenuItem(id: "altaib-bowl-1kg",  name: "Create Your Bowl (1 Kg)",
                 description: "Pick up to 10 items of approximately 100 grams each.",
                 price: 25.00,
                 image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
                 popular: false, section: "Create Your Bowl"),

        // ── Pizza Slices ─────────────────────────────────────────────────
        MenuItem(id: "altaib-ps-cheese",    name: "Cheese Pizza Slice",
                 description: "Sauce, mozzarella.",
                 price: 5.50,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-pepperoni", name: "Pepperoni Pizza Slice",
                 description: "Sauce, mozzarella, and pepperoni.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: true, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-alldressed", name: "All Dressed Pizza Slice",
                 description: "Sauce, mozzarella, pepperoni, mushrooms, and green pepper.",
                 price: 6.75,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-veggie",    name: "Veggie Pizza Slice",
                 description: "Sauce, mozzarella, black olives, mushrooms, green peppers, and fresh tomatoes.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-chicken",   name: "Chicken Pizza Slice",
                 description: "Sauce, mozzarella, chicken, and fresh tomatoes.",
                 price: 6.75,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-mexican",   name: "Mexican Pizza Slice",
                 description: "Sauce, mozzarella, spicy beef, fresh tomatoes, banana pepper, and onions.",
                 price: 6.75,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-hawaiian",  name: "Hawaiian Pizza Slice",
                 description: "Sauce, mozzarella, beef, and pineapple.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-spinach",   name: "Spinach Pizza Slice",
                 description: "Sauce, mozzarella, spinach, and black olives.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),
        MenuItem(id: "altaib-ps-tuna",      name: "Tuna Pizza Slice",
                 description: "Sauce, mozzarella, tuna, garlic, and fresh tomatoes.",
                 price: 7.00,
                 image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
                 popular: false, section: "Pizza Slices"),

        // ── Pizza ────────────────────────────────────────────────────────
        MenuItem(id: "altaib-pz-cheese",     name: "Cheese Pizza",
                 description: "Sauce, mozzarella.",
                 price: 15.18,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-pepperoni",  name: "Pepperoni Pizza",
                 description: "Sauce, mozzarella, and pepperoni.",
                 price: 17.94,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: true, section: "Pizza"),
        MenuItem(id: "altaib-pz-alldressed", name: "All Dressed Pizza",
                 description: "Sauce, mozzarella, pepperoni, mushrooms, and green pepper.",
                 price: 19.32,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-veggie",     name: "Veggie Pizza",
                 description: "Sauce, mozzarella, black olives, mushrooms, green peppers, and fresh tomatoes.",
                 price: 19.32,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-chicken",    name: "Chicken Pizza",
                 description: "Sauce, mozzarella, chicken, and fresh tomatoes.",
                 price: 20.70,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-mexican",    name: "Mexican Pizza",
                 description: "Sauce, mozzarella, spicy beef, fresh tomatoes, banana pepper, and onions.",
                 price: 20.70,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-hawaiian",   name: "Hawaiian Pizza",
                 description: "Sauce, mozzarella, beef, and pineapple.",
                 price: 20.70,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-spinach",    name: "Spinach Pizza",
                 description: "Sauce, mozzarella, spinach, and black olives.",
                 price: 20.70,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),
        MenuItem(id: "altaib-pz-tuna",       name: "Tuna Pizza",
                 description: "Sauce, mozzarella, tuna, garlic, and fresh tomatoes.",
                 price: 22.08,
                 image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                 popular: false, section: "Pizza"),

        // ── Manakish and Pies ────────────────────────────────────────────
        MenuItem(id: "altaib-mn-zaatar",       name: "Zaatar Manakish",
                 description: "Thyme, sumac, and sesame seeds.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: true, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-cheese",       name: "Cheese Manakish",
                 description: "Mozzarella and akawi cheese.",
                 price: 7.00,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-zaatarcheese", name: "Zaatar and Cheese Manakish",
                 description: "Thyme, sumac, sesame seeds, mozzarella, and akawi cheese.",
                 price: 6.00,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-kafta",        name: "Kafta Manakish",
                 description: "Ground-beef, green peppers, and kafta spices.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-sojuk",        name: "Sojuk Manakish",
                 description: "Ground-beef, sujok spices, and tomatoes.",
                 price: 11.99,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-lahmbajine",   name: "Lahmbajine Manakish",
                 description: "Ground-beef tomato puree, onions, and seven spices.",
                 price: 7.50,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-lahmbcheese",  name: "Lahmbajine and Cheese Manakish",
                 description: "Ground-beef tomato puree, onions, seven spices, and mozzarella.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-feta",         name: "Feta Manakish",
                 description: "Feta and mozzarella cheese and parsley.",
                 price: 6.50,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-spinachpie",   name: "Spinach Pie",
                 description: "Spinach, sumac, lemon, and onion.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-cheesepie",    name: "Cheese Pie",
                 description: "Mozzarella and sesame seeds.",
                 price: 5.00,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-halfhalf",     name: "Half-Spinach / Half-Cheese Pie",
                 description: "Spinach, sumac, lemon, onion, and mozzarella.",
                 price: 5.00,
                 image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-falafelswitch",name: "Falafel Sandwich",
                 description: "Crispy falafel in fresh bread with vegetables and tahini.",
                 price: 9.00,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-fetafromage",  name: "Feta Fromage",
                 description: "Feta cheese sandwich.",
                 price: 7.50,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-sojukfromage", name: "Sojok & Fromage",
                 description: "Sujok sausage and fromage cheese sandwich.",
                 price: 8.50,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-shishtaouksw", name: "Shish Taouk (Poulet)",
                 description: "Marinated grilled chicken in fresh bread.",
                 price: 11.99,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),
        MenuItem(id: "altaib-mn-shawarmaboeuf",name: "Shawarma (Boeuf)",
                 description: "Seasoned beef shawarma in fresh bread.",
                 price: 11.99,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Manakish and Pies"),

        // ── Grills ───────────────────────────────────────────────────────
        MenuItem(id: "altaib-gr-shishtaoukplate",   name: "Shish Taouk Plate",
                 description: "Marinated grilled chicken skewers served with sides.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: true, section: "Grills"),
        MenuItem(id: "altaib-gr-shawarmabeefsw",    name: "Shawarma Beef Sandwich",
                 description: "Seasoned beef shawarma wrapped in fresh bread.",
                 price: 8.75,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: true, section: "Grills"),
        MenuItem(id: "altaib-gr-shishtaouksw",      name: "Shish Taouk Sandwich",
                 description: "Marinated grilled chicken wrapped in fresh bread.",
                 price: 8.75,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-chickentriocan",    name: "Chicken Shawarma Trio",
                 description: "Served with a canned drink and a small potato.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-shawarbeefplate",   name: "Shawarma Beef Plate",
                 description: "Seasoned beef shawarma served with sides.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-falafelplate",      name: "Falafel Plate",
                 description: "Crispy falafel served with hummus, salad, and bread.",
                 price: 13.50,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-beeftrio",          name: "Beef Shawarma Trio",
                 description: "Served with a canned drink and a small potato.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-comboplate",        name: "Combo Shish Taouk & Shawarma Beef Plate",
                 description: "A combination of shish taouk and shawarma beef.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-2chickentriocan",   name: "2 Chicken Shawarma Trio",
                 description: "Served with a canned drink and a small potato.",
                 price: 18.99,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-combosw",           name: "Combo Chicken & Beef Shawarma Sandwich",
                 description: "Half chicken, half beef shawarma in fresh bread.",
                 price: 8.75,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-comboswtrio",       name: "Combo Chicken & Beef Shawarma Sandwich Trio",
                 description: "Served with a canned drink and a small potato.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1529692157254-04e20d5f70c9?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-steak",             name: "Steak",
                 description: "Grilled steak served with sides.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1546964124-0cce460da6cb?w=400&q=80",
                 popular: false, section: "Grills"),
        MenuItem(id: "altaib-gr-merguez",           name: "Merguez",
                 description: "Spiced lamb and beef sausage, grilled and served with sides.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
                 popular: false, section: "Grills"),

        // ── Sides ────────────────────────────────────────────────────────
        MenuItem(id: "altaib-sd-hummus",       name: "Hummus",
                 description: "Creamy chickpea dip with olive oil and paprika.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1576300883254-9abfa58aa809?w=400&q=80",
                 popular: true, section: "Sides"),
        MenuItem(id: "altaib-sd-poutine",      name: "Poutine",
                 description: "Fries topped with cheese curds and gravy.",
                 price: 12.00,
                 image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-fries",        name: "Fries",
                 description: "Crispy golden fries.",
                 price: 5.00,
                 image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-cheesecake",   name: "Cheesecake Slice",
                 description: "Classic New York-style cheesecake slice.",
                 price: 6.00,
                 image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-tabouleh",     name: "Tabouleh",
                 description: "Fresh parsley, bulgur, tomato, and lemon dressing.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-fatoush",      name: "Fatoush",
                 description: "Crispy pita, tomatoes, cucumber, and sumac dressing.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-hotpotato",    name: "Hot Potato",
                 description: "Seasoned potato, served hot.",
                 price: 6.00,
                 image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-basmati",      name: "Basmati Rice",
                 description: "Fluffy long-grain basmati rice.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-cabbage",      name: "Cabbage Salad",
                 description: "Fresh shredded cabbage with lemon dressing.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-baklava",      name: "Baklava Patisserie",
                 description: "Layers of filo filled with chopped nuts and honey.",
                 price: 3.50,
                 image: "https://images.unsplash.com/photo-1598110750624-2c4e5479ae61?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-saladbar",     name: "Salad Bar 100g",
                 description: "Fresh salad bar selection, per 100g.",
                 price: 2.50,
                 image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",
                 popular: false, section: "Sides"),
        MenuItem(id: "altaib-sd-poutinechicken",name: "Poutine au Poulet",
                 description: "Poutine topped with grilled chicken.",
                 price: 15.00,
                 image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80",
                 popular: false, section: "Sides"),

        // ── Drinks ───────────────────────────────────────────────────────
        MenuItem(id: "altaib-dk-coke",        name: "Coke",
                 description: "Classic Coca-Cola, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-dietcoke",    name: "Diet Coke",
                 description: "Coca-Cola Diet, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-pepsi",       name: "Pepsi",
                 description: "Pepsi cola, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-dietpepsi",   name: "Diet Pepsi",
                 description: "Pepsi Diet, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-redbull",     name: "Red Bull",
                 description: "Energy drink, 250 ml.",
                 price: 4.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-applejuice",  name: "Apple Juice",
                 description: "Cold-pressed apple juice.",
                 price: 4.50,
                 image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-perrier",     name: "Perrier",
                 description: "Sparkling natural mineral water.",
                 price: 3.00,
                 image: "https://images.unsplash.com/photo-1564419320461-6870880221ad?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-water",       name: "Water",
                 description: "Still mineral water.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1564419320461-6870880221ad?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-fanta",       name: "Fanta",
                 description: "Orange Fanta, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-sprite",      name: "Sprite",
                 description: "Sprite lemon-lime, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-7up",         name: "7 Up",
                 description: "7 Up lemon-lime soda, chilled.",
                 price: 2.00,
                 image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
                 popular: false, section: "Drinks"),
        MenuItem(id: "altaib-dk-ayran",       name: "Ayran",
                 description: "Chilled salted yogurt drink.",
                 price: 5.50,
                 image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80",
                 popular: false, section: "Drinks"),
    ]

    // MARK: Restaurants
    static let restaurants: [Restaurant] = [
        Restaurant(
            id: "smash-stack",
            name: "Smash & Stack",
            category: "burgers",
            image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
            rating: 4.8,
            reviewCount: 320,
            deliveryTime: "20-30 min",
            deliveryFee: 1.99,
            minOrder: 10.00,
            distance: "0.8 km",
            badge: .popular,
            tags: ["Burgers", "Fries", "Shakes"],
            address: "1234 Ste-Catherine W, Montreal",
            menu: [
                MenuItem(id: "ss-1", name: "Classic Smash Burger",
                         description: "Two smash patties, American cheese, pickles, onions, house sauce.",
                         price: 14.99,
                         image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
                         popular: true),
                MenuItem(id: "ss-2", name: "Double Stack Deluxe",
                         description: "Double smash patties, aged cheddar, caramelised onions, bacon, truffle aioli.",
                         price: 18.99,
                         image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
                         popular: false),
                MenuItem(id: "ss-3", name: "Truffle Fries",
                         description: "Hand-cut fries tossed in truffle oil and parmesan.",
                         price: 7.99,
                         image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80",
                         popular: true),
                MenuItem(id: "ss-4", name: "Classic Shake",
                         description: "Vanilla, chocolate, or strawberry milkshake.",
                         price: 6.99,
                         image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80",
                         popular: false),
            ]
        ),
        Restaurant(
            id: "napoli-house",
            name: "Napoli House",
            category: "pizza",
            image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80",
            rating: 4.6,
            reviewCount: 215,
            deliveryTime: "25-35 min",
            deliveryFee: 0.99,
            minOrder: 12.00,
            distance: "1.2 km",
            badge: .deal,
            tags: ["Pizza", "Italian", "Pasta"],
            address: "789 Saint-Denis St, Montreal",
            menu: [
                MenuItem(id: "nh-1", name: "Margherita",
                         description: "San Marzano tomatoes, fresh mozzarella, basil, extra virgin olive oil.",
                         price: 16.99,
                         image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                         popular: true),
                MenuItem(id: "nh-2", name: "Diavola",
                         description: "Spicy salami, mozzarella, chilli flakes, tomato.",
                         price: 18.99,
                         image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
                         popular: false),
                MenuItem(id: "nh-3", name: "Spaghetti Carbonara",
                         description: "Guanciale, egg yolk, pecorino, black pepper.",
                         price: 17.50,
                         image: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=400&q=80",
                         popular: true),
                MenuItem(id: "nh-4", name: "Tiramisu",
                         description: "Classic Italian tiramisu with espresso-soaked ladyfingers.",
                         price: 8.50,
                         image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",
                         popular: false),
            ]
        ),
        Restaurant(
            id: "sakura-roll",
            name: "Sakura Roll Co.",
            category: "sushi",
            image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80",
            rating: 4.9,
            reviewCount: 410,
            deliveryTime: "30-45 min",
            deliveryFee: 2.49,
            minOrder: 15.00,
            distance: "1.5 km",
            badge: .popular,
            tags: ["Sushi", "Japanese", "Rolls"],
            address: "450 Crescent St, Montreal",
            menu: [
                MenuItem(id: "sr-1", name: "Dragon Roll",
                         description: "Shrimp tempura, cucumber, topped with avocado and tobiko.",
                         price: 16.99,
                         image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80",
                         popular: true),
                MenuItem(id: "sr-2", name: "Spicy Tuna Roll",
                         description: "Fresh tuna, spicy mayo, cucumber, sesame seeds.",
                         price: 14.99,
                         image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80",
                         popular: true),
                MenuItem(id: "sr-3", name: "Edamame",
                         description: "Steamed salted soybeans.",
                         price: 5.99,
                         image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80",
                         popular: false),
                MenuItem(id: "sr-4", name: "Miso Soup",
                         description: "Traditional dashi miso with tofu, wakame, and green onion.",
                         price: 3.99,
                         image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80",
                         popular: false),
            ]
        ),
        Restaurant(
            id: "verde-bowl",
            name: "Verde Bowl",
            category: "salads",
            image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
            rating: 4.5,
            reviewCount: 178,
            deliveryTime: "15-25 min",
            deliveryFee: 1.49,
            minOrder: 10.00,
            distance: "0.6 km",
            badge: .new,
            tags: ["Salads", "Bowls", "Healthy"],
            address: "321 McGill College Ave, Montreal",
            menu: [
                MenuItem(id: "vb-1", name: "Green Goddess Bowl",
                         description: "Kale, quinoa, avocado, cucumber, green goddess dressing.",
                         price: 14.99,
                         image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
                         popular: true),
                MenuItem(id: "vb-2", name: "Mediterranean Bowl",
                         description: "Falafel, hummus, tomatoes, olives, feta, tahini.",
                         price: 15.99,
                         image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",
                         popular: false),
                MenuItem(id: "vb-3", name: "Smoothie",
                         description: "Blend of seasonal fruits and almond milk.",
                         price: 7.99,
                         image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80",
                         popular: false),
            ]
        ),
        Restaurant(
            id: "taco-loco",
            name: "Taco Loco",
            category: "tacos",
            image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
            rating: 4.7,
            reviewCount: 290,
            deliveryTime: "20-30 min",
            deliveryFee: 1.99,
            minOrder: 10.00,
            distance: "1.0 km",
            badge: nil,
            tags: ["Tacos", "Mexican", "Burritos"],
            address: "567 Sherbrooke W, Montreal",
            menu: [
                MenuItem(id: "tl-1", name: "Street Tacos (3)",
                         description: "Carne asada or al pastor, cilantro, onion, lime, salsa verde.",
                         price: 13.99,
                         image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80",
                         popular: true),
                MenuItem(id: "tl-2", name: "Burrito Grande",
                         description: "Rice, beans, chicken or beef, cheese, sour cream, guacamole.",
                         price: 15.99,
                         image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80",
                         popular: false),
                MenuItem(id: "tl-3", name: "Guacamole & Chips",
                         description: "Fresh guacamole with crispy tortilla chips.",
                         price: 8.99,
                         image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80",
                         popular: true),
            ]
        ),
        Restaurant(
            id: "sweet-lab",
            name: "Sweet Lab",
            category: "desserts",
            image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=600&q=80",
            rating: 4.8,
            reviewCount: 355,
            deliveryTime: "15-20 min",
            deliveryFee: 0.99,
            minOrder: 8.00,
            distance: "0.4 km",
            badge: nil,
            tags: ["Desserts", "Cakes", "Ice Cream"],
            address: "88 Laurier Ave W, Montreal",
            menu: [
                MenuItem(id: "sl-1", name: "Cookie Dough Sundae",
                         description: "Warm cookie dough, vanilla ice cream, caramel drizzle, whipped cream.",
                         price: 9.99,
                         image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80",
                         popular: true),
                MenuItem(id: "sl-2", name: "Nutella Crepe",
                         description: "Thin crepe filled with Nutella, banana, and whipped cream.",
                         price: 10.99,
                         image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80",
                         popular: true),
                MenuItem(id: "sl-3", name: "New York Cheesecake",
                         description: "Classic baked cheesecake with berry coulis.",
                         price: 8.99,
                         image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80",
                         popular: false),
            ]
        ),
        Restaurant(
            id: "al-taib",
            name: "Al Taib",
            category: "grills",
            image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
            rating: 4.7,
            reviewCount: 512,
            deliveryTime: "25-35 min",
            deliveryFee: 1.99,
            minOrder: 12.00,
            distance: "1.3 km",
            badge: .popular,
            tags: ["Grills", "Lebanese", "Pizza", "Shawarma"],
            address: "2125 Guy St, Montreal",
            menu: alTaibMenu
        ),
    ]

    // MARK: Active Order
    static let activeOrder = Order(
        id: "order-active-001",
        restaurantName: "Smash & Stack",
        restaurantImage: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
        status: .onTheWay,
        items: [
            OrderItem(name: "Classic Smash Burger", qty: 2, price: 14.99),
            OrderItem(name: "Truffle Fries",        qty: 1, price: 7.99),
        ],
        total: 39.96,
        date: "Today",
        deliveryAddress: "742 Evergreen Terrace, Montreal",
        estimatedTime: "8 min"
    )

    // MARK: Past Orders
    static let pastOrders: [Order] = [
        Order(
            id: "order-past-001",
            restaurantName: "Napoli House",
            restaurantImage: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
            status: .delivered,
            items: [
                OrderItem(name: "Margherita",         qty: 1, price: 16.99),
                OrderItem(name: "Spaghetti Carbonara", qty: 1, price: 17.50),
                OrderItem(name: "Tiramisu",            qty: 2, price: 8.50),
            ],
            total: 51.48,
            date: "Jun 5, 2026",
            deliveryAddress: "742 Evergreen Terrace, Montreal"
        ),
        Order(
            id: "order-past-002",
            restaurantName: "Sakura Roll Co.",
            restaurantImage: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80",
            status: .delivered,
            items: [
                OrderItem(name: "Dragon Roll",    qty: 2, price: 16.99),
                OrderItem(name: "Spicy Tuna Roll", qty: 1, price: 14.99),
                OrderItem(name: "Miso Soup",       qty: 2, price: 3.99),
            ],
            total: 56.95,
            date: "Jun 1, 2026",
            deliveryAddress: "742 Evergreen Terrace, Montreal"
        ),
    ]
}
